name: Deploy to firebase
on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@gh-pages
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@gh-pages
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
